language: php

php:
  - 7.2
 
before_install:
- composer self-update

before_script:
- composer install --no-interaction --prefer-source

script: 
- phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
