codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 4
  round: up
  range: "60...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: no
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
